lowpass:
  0:
    shape: [256,256,1]
    cutoff: 0
    width: 0
    path: lowpass_00.mrc
  1:
    shape: [256,256,1]
    cutoff: 0.5
    width: 0
    path: lowpass_01.mrc
  2:
    shape: [256,256,1]
    cutoff: 0.35
    width: 0.1
    path: lowpass_02.mrc
  3:
    shape: [512,256,1]
    cutoff: 0.2
    width: 0.3
    path: lowpass_03.mrc
  4:
    shape: [128,128,128]
    cutoff: 0
    width: 0
    path: lowpass_04.mrc
  5:
    shape: [128,128,128]
    cutoff: 0.5
    width: 0
    path: lowpass_05.mrc
  6:
    shape: [64,128,128]
    cutoff: 0.2
    width: 0.3
    path: lowpass_06.mrc

highpass:
  0:
    shape: [256,256,1]
    cutoff: 0
    width: 0
    path: highpass_00.mrc
  1:
    shape: [256,256,1]
    cutoff: 0.5
    width: 0
    path: highpass_01.mrc
  2:
    shape: [256,256,1]
    cutoff: 0.35
    width: 0.1
    path: highpass_02.mrc
  3:
    shape: [512,256,1]
    cutoff: 0.2
    width: 0.3
    path: highpass_03.mrc
  4:
    shape: [128,128,128]
    cutoff: 0
    width: 0
    path: highpass_04.mrc
  5:
    shape: [128,128,128]
    cutoff: 0.5
    width: 0
    path: highpass_05.mrc
  6:
    shape: [64,128,128]
    cutoff: 0.2
    width: 0.3
    path: highpass_06.mrc

bandpass:
  0:
    shape: [256,256,1]
    cutoff: [0.4,0.5]
    width: [0,0]
    path: bandpass_00.mrc
  1:
    shape: [256,512,1]
    cutoff: [0.3,0.45]
    width: [0.3,0.05]
    path: bandpass_01.mrc
  2:
    shape: [128,128,1]
    cutoff: [0.3,0.4]
    width: [0.05,0.05]
    path: bandpass_02.mrc
  3:
    shape: [128,128,128]
    cutoff: [0.2,0.45]
    width: [0.1,0.05]
    path: bandpass_03.mrc
  4:
    shape: [64,128,128]
    cutoff: [0.1, 0.3]
    width: [0,0.1]
    path: bandpass_04.mrc

remap:
  2D:  # random shape
    input: tmp_remap_2D.mrc
    fftshift: tmp_remap_2D_fftshift.mrc
    ifftshift: tmp_remap_2D_ifftshift.mrc
  3D:  # random shape
    input: tmp_remap_3D.mrc
    fftshift: tmp_remap_3D_fftshift.mrc
    ifftshift: tmp_remap_3D_ifftshift.mrc
