apply2D:
  inputs:
    - name: &input2D_0 tmp_apply2D_input_00.mrc
      shape: [ 128,128 ]
    - name: &input2D_1 tmp_apply2D_input_01.mrc
      shape: [ 411,651 ]

  tests: # scale, rotate, then shift
    0:
      input: *input2D_0
      expected: tmp_apply2D_00.mrc
      scale: [ 1,1 ]
      rotate: 10 # deg
      center: [ 64,64 ]
      shift: [ 0,0 ]
      cutoff: 0.5
      interp: INTERP_LINEAR
#    1:
#      input: *input2D_1
#      expected: tmp_apply2D_01.mrc
#      scale: [ 1,1 ]
#      rotate: 30 # deg
#      center: [ 205,325 ]
#      shift: [ 0,0 ]
#      cutoff: 0.5
#      interp: INTERP_LINEAR
#    2:
#      input: *input2D_0
#      expected: tmp_apply2D_02.mrc
#      scale: [ 1,1 ]
#      rotate: 45 # deg
#      center: [ 256,256 ]
#      shift: [ -30,30 ]
#      cutoff: 0.5
#      interp: INTERP_LINEAR
#    3:
#      input: *input2D_1
#      expected: tmp_apply2D_03.mrc
#      scale: [ 1,1 ]
#      rotate: 45 # deg
#      center: [ 205,325 ]
#      shift: [ -30,30 ]
#      cutoff: 0.5
#      interp: INTERP_LINEAR
#    4:
#      input: *input2D_0
#      expected: tmp_apply2D_04.mrc
#      scale: [ 1,1.5 ]
#      rotate: -45 # deg
#      center: [ 224,224 ]
#      shift: [ 0,60 ]
#      cutoff: 0.5
#      interp: INTERP_LINEAR
#    5:
#      input: *input2D_1
#      expected: tmp_apply2D_05.mrc
#      scale: [ 1,1.5 ]
#      rotate: -45 # deg
#      center: [ 173,261 ]
#      shift: [ 0,60 ]
#      cutoff: 0.5
#      interp: INTERP_LINEAR


apply3D:
  inputs:
    - name: &input3D_0 tmp_apply3D_input_00.mrc
      shape: [ 256,256,256 ]
    - name: &input3D_1 tmp_apply3D_input_01.mrc
      shape: [ 511,256,257 ]

  tests: # scale, rotate, then shift
    0:
      input: *input3D_0
      expected: tmp_apply3D_00.mrc
      scale: [ 1,1,1 ]
      rotate: [30,0,0] # ZYZ intrinsic deg
      center: [ 128,128,128 ]
      shift: [ 0,0,0 ]
      cutoff: 0.5
      interp: INTERP_LINEAR
    1:
      input: *input3D_1
      expected: tmp_apply3D_01.mrc
      scale: [ 1,1,1 ]
      rotate: [30,0,0] # ZYZ intrinsic deg
      center: [ 255,128,128 ]
      shift: [ 0,0,0 ]
      cutoff: 0.5
      interp: INTERP_LINEAR
    2:
      input: *input3D_0
      expected: tmp_apply3D_02.mrc
      scale: [ 1,1,1 ]
      rotate: [45,0,0] # ZYZ intrinsic deg
      center: [ 128,128,128 ]
      shift: [ -40,20,0 ]
      cutoff: 0.5
      interp: INTERP_LINEAR
    3:
      input: *input3D_1
      expected: tmp_apply3D_03.mrc
      scale: [ 1,1,1 ]
      rotate: [45,0,0] # ZYZ intrinsic deg
      center: [ 255,128,128 ]
      shift: [ -40,20,0 ]
      cutoff: 0.5
      interp: INTERP_LINEAR
    4:
      input: *input3D_0
      expected: tmp_apply3D_04.mrc
      scale: [ 1.5,1,1 ]
      rotate: [-30,0,0] # ZYZ intrinsic deg
      center: [ 96,96,96 ]
      shift: [ 0,50,0 ]
      cutoff: 0.5
      interp: INTERP_LINEAR
    5:
      input: *input3D_1
      expected: tmp_apply3D_05.mrc
      scale: [ 1.5,1,1 ]
      rotate: [-30,0,0] # ZYZ intrinsic deg
      center: [ 223,96,96 ]
      shift: [ 0,50,0 ]
      cutoff: 0.5
      interp: INTERP_LINEAR


shift:
  2D:
    shape: [ 64,71 ]
    shift: [ -32,25 ]
    input: tmp_shift2D_input.mrc
    output: tmp_shift2D_00.mrc

  3D:
    shape: [ 64,71,68 ]
    shift: [ -32,25,33 ]
    input: tmp_shift3D_input.mrc
    output: tmp_shift3D_00.mrc
